### PR TITLE
Adopt GoDoc and rename it to Ri

### PR DESCRIPTION
**Pull request by mluts**
Hi, i love ruby and was envious about `vim-go`'s `GoDoc`, so i decided to adopt their code into `vim-ruby`. 

It's a convenient way to discover rdoc while staying in vim.

Would be grateful if this will be merged into master, feel free to modify.

### CODE REVIEW

**Comment by tpope** [comment]
I think if you want something like this, the way to do it is a generic plugin that looks at `'keywordprg'`. I don't think copying and pasting the same code everywhere is the way to go, and even if I accepted it as the best pragmatic course of action, I wouldn't really think it belonged in the standard Ruby ftplugin. It's plenty bloated already.

**Comment by mluts** [comment]
@tpope What i'm struggling with, is that i can't scroll up/down the output of `ri` in neovim (sorry, i prefer it), the shortest way to achieve that would be `set keywordprg=:term\ ri`. Already added it to my own vimrc, but other users will suffer from this in default `vim-ruby` setup and that is little sad.

**Comment by mluts** [comment]
@tpope What i'm struggling with, is that i can't scroll up/down the output of `ri` in neovim (sorry, i prefer it), the shortest way to achieve that would be `set keywordprg=:term\ ri`. Already added it to my own vimrc, but other users will suffer from this in default `vim-ruby` setup and that is little sad.

**Comment by mluts** [comment]
@tpope What i'm struggling with, is that i can't scroll up/down the output of `ri` in neovim (sorry, i prefer it), the shortest way to achieve that would be `set keywordprg=:term\ ri`. Already added it to my own vimrc, but other users will suffer from this in default `vim-ruby` setup and that is little sad.

**Comment by mluts** [comment]
@tpope What i'm struggling with, is that i can't scroll up/down the output of `ri` in neovim (sorry, i prefer it), the shortest way to achieve that would be `set keywordprg=:term\ ri`. Already added it to my own vimrc, but other users will suffer from this in default `vim-ruby` setup and that is little sad.

**Comment by tpope** [comment]
A generic plugin that calls `:term` plus `'keywordprg'` on the word under the cursor would be pretty short.

**Pull request closed without merging**
