### PR TITLE
Add ruby_foldable_groups option

### PR DESCRIPTION
**Pull request by bootleq**
Implementation of my [proposal](https://github.com/vim-ruby/vim-ruby/issues/258#issuecomment-128983122) at #258.

Usage of `ruby_foldable_groups` is written in doc (ft-ruby-syntax.txt).

Also prepared example files for checking (manually).

### CODE REVIEW

**Comment by dkearns** [comment]
Thanks.  I'm happy to merge this or something similar.

Does anyone have any objections?

**Comment by bruno-** [comment]
Hi,
I'm so glad I found this PR! I was looking for this feature for a long time, awesome work @bootleq 

Here are the steps I did to test this locally:

- `cd` to local `vim-ruby` plugin installation
- `$ git fetch origin pull/272/head:foldable` to pull this PR
- `$ git checkout foldable`

I've tried setting `g:ruby_foldable_groups` variable to a couple values and all things worked.

:+1: for merging this

**Comment by janko-m** [comment]
It would be really awesome if this was part of vim-ruby :+1:

**Comment by AndrewRadev** [comment]
I'm sorry for taking so long to get around to this PR.

I appreciate your work, @bootleq, and I definitely appreciate you going to extra mile to document it as well. I don't like the duplication with the syntax regions, but I guess it's the best way to implement it, and it's definitely a useful feature.

I notice there's a few files that generate example ruby files. Those are fine, I guess, but it seems like you've also committed the generated files? Could you remove those from the PR? As long as there are instructions on how to generate them, there's no point in having them in the repository.

You'd also need to merge master. It would probably be a conflict in the syntax definitions, I'm afraid. Once you do that, and take care of those example files, I'll go ahead and merge this.

**Comment by bootleq** [comment]
Hi, @AndrewRadev, thank you very much for reviewing.
I've merged master and actually using this branch for days. I think it's ready to prepare merging.

**Comment by AndrewRadev** [comment]
:+1:

**Pull request merged**
