### PR TITLE
easier test debugging

### PR DESCRIPTION
**Pull request by nerdrew**
This enables verbose mode for the indent command then prints the verbose output on test failures. Thoughts?

### CODE REVIEW

**Comment by AndrewRadev** [comment]
That's not a bad idea, I guess. I generally use `Decho`, since it gives me better output for the results, but I guess this is fine too. Might be easier to get information from people that have problems I can't reproduce on my setup, though I think these are rare cases.

I don't generally use tests for debugging issues, since it seems easier to just experiment with a running Vim. Still, I wouldn't mind particularly mind having the output. I don't like that it writes the contents in a `messages.txt` file in the main directory, though, I'd rather have it in some tempfile. Could you try to put the output in a temporary file instead? https://ruby-doc.org/stdlib-2.3.3/libdoc/tempfile/rdoc/Tempfile.html

**Comment by nerdrew** [comment]
Updated to use `Tempfile`. Sorry that took so long :)

**Comment by AndrewRadev** [comment]
No worries, I'm not particularly good about keeping up with this stuff myself, so I can sympathize :).

I tried the PR locally, but, to be honest, it seems like it's causing more problems than it solves. Using `verbosefile` only has effect when we use the `12verbose` command, and that means getting *a lot* of extra output, like what function was called, including nesting. It might be possible to filter it out, but it seems like it's easier to just debug issues manually, if a test fails.

What part of the PR do you use when trying to debug vim-ruby? If the important bit for you is using `echomsg` instead of `Decho`, we can do that without trying to fit it into the specs. Would also be nice to output the `"Running: ".callback_name` lines as well.

**Comment by nerdrew** [comment]
Eh, personal preference thing I guess. No problem. I'll close the PR.

**Pull request closed without merging**
