### PR TITLE
Add motions and text-objects for Ruby do / end blocks

### PR DESCRIPTION
**Pull request by reentim**
Not sure if others feel this belongs in vim-ruby, but I find it useful.

### CODE REVIEW

**Comment by AndrewRadev** [comment]
These do seem like useful mappings. I'm not sure if we can safely add them to vim-ruby, though. The mappings for `[[`, `[m`, and the like are *existing* mappings that don't work well for ruby, so, the plugin "fixes" them. They serve the same purpose they were created for. On the other hand the `[b` mappings are brand new, and could shadow user-defined mappings. If I have a global `[b` mapping, vim-ruby would silently override it without much of a warning. The [unimpaired](https://github.com/tpope/vim-unimpaired) plugin is one example that might stop working in ruby files because of this.

There's a setting called `no_ruby_maps`, but that would affect all mappings. A second setting might help, but it might still be difficult to discover that ruby is overriding your maps, and, in general, we try to (unsuccessfully) avoid too many settings.

As for the `ib` and `ab` mappings, those already exist, and are supposed to work the same as `i(` and `a(`. To be honest, I always use the `(` variants, because they seem more intuitive, but it does seem like it would be a surprising change to someone who's used to it.

Different keybindings for the mappings might help, but I can't really think of anything that makes consistent sense. The functionality could also be done externally if the script-local functions were exposed as autoloaded ones, though I will admit they don't seem super complicated or ruby-specific.

I'm also not the main maintainer for this particular area of vim-ruby, so I'd appreciate some input from @tpope, when he has the time.

**Comment by tpope** [comment]
You nailed it. I'm not really comfortable with using a filetype plugin that ships with Vim as a place to introduce new map conventions. I could maybe see overriding `[#` and `]#`, but that's a confusing mnemonic *and* kind of awkward to type, so I'm not sure it's worth it?

**Comment by reentim** [comment]
Thanks for the response! I suspected that might be the case, and totally overlooked the collision with `ib` `ab` — whoops.

After using it, I also realised that since blocks can nest, you ought to be able to (as with the tag object) repeat the motion while visually selecting, to grow the selection to the encapsulating block, which this lacks. Back to the drawing board, I suppose.

**Comment by tpope** [comment]
FWIW I don't think I ever got `iM` to nest, and I can't even tell for sure because it appears to be broken. I think the issue is a variant of https://github.com/tpope/vim-endwise/pull/93. Anyways these stupid motion maps are hard, and visual mode text objects are next to impossible.

**Pull request closed without merging**
