### PR TITLE
Fix completion issue about variables with vartype = "gets"

### LINKED ISSUE #228: Vim freezes when performing autocompletion
Edit a new ruby file with `vim --noplugin blah.rb`, then:

    n = gets.to_i
    n.<C-x><C-o>

Then vim freezes..

And here is the output of `vim --version`:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 19 2014 18:47:11)
Included patches: 1-410
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib
```

### PR DESCRIPTION
**Pull request by cheuk-fung**
"gets" cannot be a valid vartype, otherwise
`eval("#{vartype}.instance_methods")` would cause vim to freeze.

This fixes #228

### CODE REVIEW

**Comment by kriox26** [comment]
This totally fixes that issue!!!! I've just did the modifications you did to the rubycomplete.vim file and now it's working, please merge this pull request, i've seen a lot of guys/girls with the same problem!!

**Comment by tpope** [comment]
I won't normally go anywhere near the completion but I guess this looks pretty safe.

**Comment by segfault** [comment]
Looks ok to me as well.

**Comment by JikkuJose** [comment]
Will this get merged or will have to pull from this specific fork to get it?

**Comment by kriox26** [comment]
This has already been merged, update your local repo and everything will work just fine!

**Comment by kriox26** [comment]
[Here](https://github.com/vim-ruby/vim-ruby/commits/master) you can see that the 9 of june this was merged!!

**Comment by JikkuJose** [comment]
Thanks! I didn't notice it!

**Pull request closed without merging**
